// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylnywzlvcreanyhancke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlsbnl3emx2Y3JlYW55aGFuY2tlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MDcxNDQsImV4cCI6MjA1NjM4MzE0NH0.O2UZRbvVTpDQJz9cAZKm86Wj1UmGCHblvDe1QABsuls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);